services:
  postgres_test:
    image: postgres:16
    container_name: whale_postgres_test
    restart: unless-stopped
    environment:
      POSTGRES_DB: whale_test_db
      POSTGRES_USER: whale_test
      POSTGRES_PASSWORD: whale_test_pass
    ports:
      - "5433:5432" # Use a different host port
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U whale_test -d whale_test_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis_test:
    image: redis:7
    container_name: whale_redis_test
    restart: unless-stopped
    ports:
      - "6380:6379" # Use a different host port
    volumes:
      - redis_test_data:/data

volumes:
  postgres_test_data:
  redis_test_data: 